project:
  type: website
  output-dir: docs

website:
  title: "My DSCI310 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

# overwrite any render-on-save option
editor:
  render-on-save: true


